In [3]:
import pandas as pd

In [4]:
fake_df =pd.read_csv("Dataset/Fake.csv")
true_df =pd.read_csv("Dataset/True.csv")

In [5]:
fake_df.head(10)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017"
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017"
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017"
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017"
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017"

In [6]:
fake_df.shape

(23481, 4)

In [7]:
fake_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  str
 1   text     23481 non-null  str
 2   subject  23481 non-null  str
 3   date     23481 non-null  str
dtypes: str(4)
memory usage: 733.9 KB

In [8]:
fake_df.columns

Index(['title', 'text', 'subject', 'date'], dtype='str')

In [13]:
fake_df.dtypes

title      str
text       str
subject    str
date       str
dtype: object

In [12]:
fake_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [28]:
fake_df.sample(1)

,title,text,subject,date
7413,Trump Supporters Show They’re Not As Crazy As...,The majority of America has been wondering who...,News,"March 19, 2016"